[package]
name = "custom_rust_dist"
version = "0.1.0-alpha.1"
edition = "2021"
description = "Manage Rust toolchain and a set of extra tools with ease"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
home = "0.5.9"
indicatif = "0.17"
reqwest = { version = "0.12", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }
url = "2"
libc = "0.2"