[[packages]]
name = "XXX Community"
version = "1.80.1"
desc = "Description for community version"
info = '''
# Changelog
This is the initial build, includes:
- Rust 1.80.1 version
- blah blah blah
- ...
'''
manifest-url = "https://example.com/path/to/manifest-1.80.1"

[[packages]]
name = "XXX Community"
version = "1.81.0"
desc = "Description for community version"
info = '''
# Changelog
- add new tool support: hello_world
- ...
'''
manifest-url = "https://example.com/path/to/manifest-1.81.0"

[[packages]]
name = "XXX LTS"
version = "1.80.1"
desc = "Description for LTS version"
info = '''
# Changelog
This is the initial build, includes:
- Rust 1.80.1 version
- blah blah blah
- ...
'''
manifest-url = "https://example.com/path/to/manifest-1.80.1"
