name = "玄武 Rust 一站式开发套件"
version = "stable v1.82.0"

[rust]
version = "1.82.0"
group = "Rust"
components = ["clippy", "rustfmt", "rust-src", "rust-docs"]
optional-components = ["llvm-tools", "rustc-dev"]

[rust.profile]
name = "minimal"
verbose-name = "Rust 工具链"
description = "Rust 官方工具链，包含 rustc (编译器), rust-std (标准库), cargo (包管理) 等工具"

[tools.descriptions]
llvm-tools = "包含 LLVM 工具的集合"
rustc-dev = "将编译器作为库来内部 API。大多数用户不需要这个; 仅当开发链接到编译器的工具时才需要它, 例如对 Clippy 进行修改"
mingw64 = "编译器在 x86_64 Windows GNU 环境下的依赖组件"
typos = "源代码拼写检查器，用于查找并纠正源代码中的拼写错误"
cargo-nextest = "新一代 Rust 项目测试运行程序，相比传统 cargo test 而言更快速，界面更简洁明了"

[tools.group]
"后端编译工具链" = ["mingw64"]
"优选Rust开发工具" = ["typos", "cargo-nextest"]

[tools.target.x86_64-pc-windows-gnu]
mingw64 = { required = true, url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev0.7z", version = "14.2.0-rt_v12-rev0" }
# `-msvc` can also be used here as long as these are built.
cargo-nextest = { optional = true, version = "0.9.84", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/cargo-nextest/cargo-nextest-0.9.84-x86_64-pc-windows-msvc.zip" }
typos = { optional = true, version = "1.27.3", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/typos/typos-v1.27.3-x86_64-pc-windows-msvc.zip" }

[tools.target.x86_64-pc-windows-msvc]
cargo-nextest = { optional = true, version = "0.9.84", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/cargo-nextest/cargo-nextest-0.9.84-x86_64-pc-windows-msvc.zip" }
typos = { optional = true, version = "1.27.3", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/typos/typos-v1.27.3-x86_64-pc-windows-msvc.zip" }

[tools.target.x86_64-unknown-linux-gnu]
cargo-nextest = { optional = true, version = "0.9.84", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/cargo-nextest/cargo-nextest-0.9.84-x86_64-unknown-linux-gnu.tar.gz" }
# `-musl` target built binary still works here
typos = { optional = true, version = "1.27.3", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/typos/typos-v1.27.3-x86_64-unknown-linux-musl.tar.gz" }
