[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4", features = ["std"] }
time = { version = "0.3", features = ["formatting", "macros", "local-offset"] }
