name: GUI Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'rim_gui/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'rim_gui/**'

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  gui-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-latest' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: run clippy
        run: cargo clippy --no-deps -p rim-gui -- -D warnings
      - name: run tests
        run: cargo test -p rim-gui --verbose
