name: Standard-Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace --verbose
    - name: Clippy
      run: cargo clippy --all
    - name: Formatting tests
      run: cargo fmt --all --check
    - name: Run tests
      run: cargo test --verbose
