[package]
name = "installer"
version = "0.0.1-alpha.1"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
cfg-if = "1.0.0"
iced = { version = "0.9.0", features = ["image"], optional = true }

[features]
default = []
debug = []
iced-gui = ["dep:iced"]
